[package]
name = "sysu-templates"
version = "0.1.0"
entrypoint = "lib.typ"
authors = [ "John Smith <johnsmith0x3f@gmail.com>" ]
license = "MIT"
description = "Templates for Sun Yat-sen University (SYSU) documents."
